### ISSUE TITLE
Hello, I have a small problem.

### ISSUE THREAD

**Issue by RikkaTotsuka** [rhenwinch/Auto-SMMO#1]
I've been using your app for a long time, and I've made some small changes to it, nothing too big. Recently the smmo developer made an update that changed the API that collects materials when walking, which is causing a 404 error. I made some changes and tried to fix it, but I couldn't. The most I got was a 405 error, as if the API request method was different. Could you help me?
![image](https://github.com/user-attachments/assets/b0dd0c2a-6e0d-4759-97aa-6ebf1b30cd8e)

**Comment by rhenwinch** [comment]
Sure thing!

Can you send here the stacktrace error + link the github repo of your code?

I'll try to get back to you on the weekend :smile:

**Comment by RikkaTotsuka** [comment]
Thank you XD <3 https://github.com/RikkaTotsuka/AutoMMO-copy

com.xcape.simplemmomod.data.smmo_tasks.CannotGatherMaterials: Could not gather material: Unexpected code Response{protocol=h2, code=404, message=, url=https://simple-mmo.com/api/crafting/material/gather/159261077?new_page=true}
	at com.xcape.simplemmomod.data.smmo_tasks.LootActionsImpl.obtainMaterials(LootActionsImpl.kt:120)
	at com.xcape.simplemmomod.data.smmo_tasks.LootActionsImpl$obtainMaterials$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)


It seems that the smmo developer modified the link that is generated when finding an item while walking in the game, I tried to put a proxy to check the traffic but I couldn't
the other methods are fully functional

**Comment by rhenwinch** [comment]
Your repo doesnt contain the whole android code, could you re-check?

**Comment by RikkaTotsuka** [comment]
Sorry XD I accidentally changed the link. I had two identical repositories, one without the Android code and the other with it. Here it is https://github.com/RikkaTotsuka/Auto-SMMOCopy

**Comment by RikkaTotsuka** [comment]
I hope you haven't forgotten about me ^^

**Comment by rhenwinch** [comment]
Hi @RikkaTotsuka!  Sorry for the late reply, I might push a thing or two later here on my repo.

_(Here's some info I've collected. Dont mind me yapping here, im just gonna log this one for later so I won't have to re-test their site)_

Based on what I've checked, this is the new endpoint:
```kotlin
val GATHER_MATERIAL_URL = "$BASE_URL/api/api/crafting/material/gather/%s?expires=xxx&signature=xxxxx"
```

As you can see there are newly introduced queries `signature` and `expires`. I think- with this new shit they added -the `GATHER_MATERIAL_URL` should be removed and just get the endpoint directly from the item gathering page, which is from here:
https://github.com/rhenwinch/Auto-SMMO/blob/5910295438871c63d804ded3e8c4e46501401284/app/src/main/java/com/xcape/simplemmomod/data/smmo_tasks/LootActionsImpl.kt#L60-L63

They also changed its POST body requirement. It previously used this:
https://github.com/rhenwinch/Auto-SMMO/blob/5910295438871c63d804ded3e8c4e46501401284/app/src/main/java/com/xcape/simplemmomod/data/smmo_tasks/LootActionsImpl.kt#L85

Then changed it to something like:
```json
{"quantity":1,"id":123456}
```
---

### Some questions:
1. Are there more endpoints that has been broken?
2. (offtopic but) Have you been using a release (using full R8 mode) version of the app?

The reason why I asked no. 2 is because after a whole ass year of Android learning I just realized some things:
- my code is not performance optimized;
- the global `OkHttpClient` is leaking memory; and
- my compose code sucks especially for the NavigationDrawer.

**Comment by RikkaTotsuka** [comment]
Hello, I'm glad you're still here, I don't mind the delay, the code is yours XD, I've been using it for about a year, I got your version and used it for two months until I noticed some errors and crashes.

After that time I noticed that the log, after generating a lot of information, ended up crashing the app when I entered it after leaving it running in the background.
When I realized this, I put a 60-second loop that "creates a kind of flag" to clear the log, after that I no longer had problems with crashing when entering the app after being in the background.


Another thing I noticed in the app after using it for a while was that it always put dexterity to level up even if you switched to another skill it leveled up dexterity.
I made a small adjustment, I don't even remember what I changed if I'm not mistaken, there was something in the code that was making it always choose dex, I just deleted it and the problem was solved, it started to level up what you chose.


As it's been a while since I messed with the log and dexterity, I can't say which part of the code I messed with, but I put some notes in Portuguese, they were simple things as you can imagine, Now we have this stupid API/endpoint problem because of the recent update, but I think you found the solution and I'll try to do something with your information. (I've literally just started learning how to code Android apps now, and I started using your app) so don't expect too much.

**Comment by rhenwinch** [comment]
I see. Btw, it seems like this repo [RikkaTotsuka/Auto-SMMOCopy](https://github.com/RikkaTotsuka/Auto-SMMOCopy) has not been updated yet. Could you commit and push your updates?

**Comment by RikkaTotsuka** [comment]
Ah, that's because I made the updates before making the repository and I'm new to git, I don't understand much, but I can find the changes made and update them.

**Comment by RikkaTotsuka** [comment]
Ah, that's because I made the updates before making the repository and I'm new to git, I don't understand much, but I can find the changes made and update them.

**Comment by rhenwinch** [comment]
most issues on this thread has been fixed now. if a new issue comes up, just create a new one instead. thanks!

also check out [1.0.0](https://github.com/rhenwinch/Auto-SMMO/releases/tag/1.0.0)

**Comment by RikkaTotsuka** [comment]
Thank you, I posted the commit you requested, I apologize for the delay, I was in bed yesterday XD
https://github.com/RikkaTotsuka/Auto-SMMOCopy/commits/master/
